version: '3.9'

services:
  db:
    restart: always
    container_name: db_postgis
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  web:
    build: .
    command: poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_postgis:5432/${POSTGRES_DB}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
