version: '3.9'

services:
  db:
    restart: always
    container_name: postgres
    image: postgis/postgis:latest
    env_file:
      - config/.env
    environment:
      - POSTGRES_HOST=db
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    networks:
      - db

  web:
    build:
      target: prod
      context: .
      dockerfile: ./Dockerfile
    image: on1x/app_prod
    container_name: app_django
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - config/.env
    environment:
      - DEBUG=False
    networks:
      - db
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "4", "--threads", "2", "config.wsgi:application"]

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  db:
  