version: "3.9"
services:

  db:
    restart: always
    container_name: db_postgis
    image: postgis/postgis:latest 
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: places
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432