version: '3.9'

services:
  db:
    restart: always
    container_name: postgres
    image: postgis/postgis:latest
    env_file:
      - config/.env
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    network_mode: host

  web:
    build:
      target: prod
      context: .
      dockerfile: ./Dockerfile
    image: on1x/app_prod
    container_name: app_django
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - config/.env
    network_mode: host
   
volumes:
  postgres_data:
  static_volume:
  media_volume:

  